name: 'autoencoder'
#****** Data settings ******
image_size: 128 # resize input images to this size
# pad_channel: 16
resize_size: [128,128,128]
dataroot: "/root/data1/CTSpine1K/mid_h5_new"

CT_MEAN_STD: [0.0, 1.0]
XRAY1_MEAN_STD: [0.0, 1.0]
XRAY2_MEAN_STD: [0.0, 1.0]
XRAY1_MIN_MAX: [0, 255]
XRAY2_MIN_MAX: [0, 255]
CT_MIN_MAX: [-500, 2000]

fine_size: 128
fine_size_cond: 128
ct_channel: 128
xray_channel: 1

train_datasetfile: "./data/train.txt"
val_datasetfile: "./data/test.txt"
dis_datasetfile: "./data/dis.txt"



output_dir : "./logs/${config.name}"  # the traning logs saved
  
model:
  base_learning_rate: 1.0e-4
  sync_dist: True
  # params:
  monitor: "val/rec_loss"
  embed_dim: 4
  lossconfig:
    # target: ldm.modules.losses.LPIPSWithDiscriminator
    # params:
    disc_start: 10000
    kl_weight: 1.0e-4
    disc_weight: 0.5
    highlow_weight: 0
    high_limit: 0.04
    low_limit: 0.04
    disc_in_channels: 1
    perceptual_weight: 0

  ddconfig:
    double_z: True
    z_channels: 4
    resolution: 128
    in_channels: 1
    out_ch: 1
    ch: 32
    ch_mult: [1,2,4,4]  # num_down = len(ch_mult)-1  #[1,2,2,2,4]  [1,2,4,4]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0

trainer:
  benchmark: True
  accumulate_grad_batches: 1
  # single-GPU default; override at runtime as needed
  devices: [0]
  accelerator: "auto"
  max_epochs: 1000
  fast_dev_run: False
  precision: "32"
